/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as CustomWebsitesRouteImport } from './routes/custom-websites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as TemplatesSlugIndexRouteImport } from './routes/templates.$slug.index'
import { Route as TemplatesSlugPreviewRouteImport } from './routes/templates.$slug.preview'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomWebsitesRoute = CustomWebsitesRouteImport.update({
  id: '/custom-websites',
  path: '/custom-websites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesSlugIndexRoute = TemplatesSlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesSlugPreviewRoute = TemplatesSlugPreviewRouteImport.update({
  id: '/$slug/preview',
  path: '/$slug/preview',
  getParentRoute: () => TemplatesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/custom-websites': typeof CustomWebsitesRoute
  '/pricing': typeof PricingRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/templates/': typeof TemplatesIndexRoute
  '/templates/$slug/preview': typeof TemplatesSlugPreviewRoute
  '/templates/$slug/': typeof TemplatesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/custom-websites': typeof CustomWebsitesRoute
  '/pricing': typeof PricingRoute
  '/templates': typeof TemplatesIndexRoute
  '/templates/$slug/preview': typeof TemplatesSlugPreviewRoute
  '/templates/$slug': typeof TemplatesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/custom-websites': typeof CustomWebsitesRoute
  '/pricing': typeof PricingRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/templates/': typeof TemplatesIndexRoute
  '/templates/$slug/preview': typeof TemplatesSlugPreviewRoute
  '/templates/$slug/': typeof TemplatesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/custom-websites'
    | '/pricing'
    | '/templates'
    | '/templates/'
    | '/templates/$slug/preview'
    | '/templates/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/custom-websites'
    | '/pricing'
    | '/templates'
    | '/templates/$slug/preview'
    | '/templates/$slug'
  id:
    | '__root__'
    | '/'
    | '/custom-websites'
    | '/pricing'
    | '/templates'
    | '/templates/'
    | '/templates/$slug/preview'
    | '/templates/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomWebsitesRoute: typeof CustomWebsitesRoute
  PricingRoute: typeof PricingRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-websites': {
      id: '/custom-websites'
      path: '/custom-websites'
      fullPath: '/custom-websites'
      preLoaderRoute: typeof CustomWebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/$slug/': {
      id: '/templates/$slug/'
      path: '/$slug'
      fullPath: '/templates/$slug/'
      preLoaderRoute: typeof TemplatesSlugIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/$slug/preview': {
      id: '/templates/$slug/preview'
      path: '/$slug/preview'
      fullPath: '/templates/$slug/preview'
      preLoaderRoute: typeof TemplatesSlugPreviewRouteImport
      parentRoute: typeof TemplatesRoute
    }
  }
}

interface TemplatesRouteChildren {
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  TemplatesSlugPreviewRoute: typeof TemplatesSlugPreviewRoute
  TemplatesSlugIndexRoute: typeof TemplatesSlugIndexRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesIndexRoute: TemplatesIndexRoute,
  TemplatesSlugPreviewRoute: TemplatesSlugPreviewRoute,
  TemplatesSlugIndexRoute: TemplatesSlugIndexRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomWebsitesRoute: CustomWebsitesRoute,
  PricingRoute: PricingRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
