/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as CustomWebsitesRouteImport } from './routes/custom-websites'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as PricingStartRouteImport } from './routes/pricing.start'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as TemplatesSlugIndexRouteImport } from './routes/templates.$slug.index'
import { Route as TemplatesSlugPreviewRouteImport } from './routes/templates.$slug.preview'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomWebsitesRoute = CustomWebsitesRouteImport.update({
  id: '/custom-websites',
  path: '/custom-websites',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesRoute,
} as any)
const PricingStartRoute = PricingStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => PricingRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const TemplatesSlugIndexRoute = TemplatesSlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesSlugPreviewRoute = TemplatesSlugPreviewRouteImport.update({
  id: '/$slug/preview',
  path: '/$slug/preview',
  getParentRoute: () => TemplatesRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/custom-websites': typeof CustomWebsitesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRouteWithChildren
  '/templates': typeof TemplatesRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/pricing/start': typeof PricingStartRoute
  '/templates/': typeof TemplatesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/templates/$slug/preview': typeof TemplatesSlugPreviewRoute
  '/templates/$slug/': typeof TemplatesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/custom-websites': typeof CustomWebsitesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/pricing/start': typeof PricingStartRoute
  '/templates': typeof TemplatesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/templates/$slug/preview': typeof TemplatesSlugPreviewRoute
  '/templates/$slug': typeof TemplatesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/custom-websites': typeof CustomWebsitesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRouteWithChildren
  '/templates': typeof TemplatesRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/pricing/start': typeof PricingStartRoute
  '/templates/': typeof TemplatesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/templates/$slug/preview': typeof TemplatesSlugPreviewRoute
  '/templates/$slug/': typeof TemplatesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/custom-websites'
    | '/how-it-works'
    | '/mcp'
    | '/pricing'
    | '/templates'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/pricing/start'
    | '/templates/'
    | '/.mcp/invoke-tool/$tool'
    | '/templates/$slug/preview'
    | '/templates/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/custom-websites'
    | '/how-it-works'
    | '/mcp'
    | '/pricing'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/pricing/start'
    | '/templates'
    | '/.mcp/invoke-tool/$tool'
    | '/templates/$slug/preview'
    | '/templates/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/custom-websites'
    | '/how-it-works'
    | '/mcp'
    | '/pricing'
    | '/templates'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/pricing/start'
    | '/templates/'
    | '/.mcp/invoke-tool/$tool'
    | '/templates/$slug/preview'
    | '/templates/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CustomWebsitesRoute: typeof CustomWebsitesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  McpRoute: typeof McpRoute
  PricingRoute: typeof PricingRouteWithChildren
  TemplatesRoute: typeof TemplatesRouteWithChildren
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-websites': {
      id: '/custom-websites'
      path: '/custom-websites'
      fullPath: '/custom-websites'
      preLoaderRoute: typeof CustomWebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/pricing/start': {
      id: '/pricing/start'
      path: '/start'
      fullPath: '/pricing/start'
      preLoaderRoute: typeof PricingStartRouteImport
      parentRoute: typeof PricingRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$slug/': {
      id: '/templates/$slug/'
      path: '/$slug'
      fullPath: '/templates/$slug/'
      preLoaderRoute: typeof TemplatesSlugIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/$slug/preview': {
      id: '/templates/$slug/preview'
      path: '/$slug/preview'
      fullPath: '/templates/$slug/preview'
      preLoaderRoute: typeof TemplatesSlugPreviewRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PricingRouteChildren {
  PricingStartRoute: typeof PricingStartRoute
}

const PricingRouteChildren: PricingRouteChildren = {
  PricingStartRoute: PricingStartRoute,
}

const PricingRouteWithChildren =
  PricingRoute._addFileChildren(PricingRouteChildren)

interface TemplatesRouteChildren {
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  TemplatesSlugPreviewRoute: typeof TemplatesSlugPreviewRoute
  TemplatesSlugIndexRoute: typeof TemplatesSlugIndexRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesIndexRoute: TemplatesIndexRoute,
  TemplatesSlugPreviewRoute: TemplatesSlugPreviewRoute,
  TemplatesSlugIndexRoute: TemplatesSlugIndexRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CustomWebsitesRoute: CustomWebsitesRoute,
  HowItWorksRoute: HowItWorksRoute,
  McpRoute: McpRoute,
  PricingRoute: PricingRouteWithChildren,
  TemplatesRoute: TemplatesRouteWithChildren,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
