/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as TemplatesSlugPreviewRouteImport } from './routes/templates.$slug.preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesSlugPreviewRoute = TemplatesSlugPreviewRouteImport.update({
  id: '/templates/$slug/preview',
  path: '/templates/$slug/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/templates/$slug/preview': typeof TemplatesSlugPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/templates/$slug/preview': typeof TemplatesSlugPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/templates/$slug/preview': typeof TemplatesSlugPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/templates/' | '/templates/$slug/preview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/templates' | '/templates/$slug/preview'
  id: '__root__' | '/' | '/templates/' | '/templates/$slug/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  TemplatesSlugPreviewRoute: typeof TemplatesSlugPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$slug/preview': {
      id: '/templates/$slug/preview'
      path: '/templates/$slug/preview'
      fullPath: '/templates/$slug/preview'
      preLoaderRoute: typeof TemplatesSlugPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  TemplatesSlugPreviewRoute: TemplatesSlugPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
